dist: trusty
language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -U pip
    - pip install -U -e .[cpu,develop,examples]
script:
    - PYTHONPATH=$PWD:$PYTHONPATH py.test
    - jupyter-nbconvert --ExecutePreprocessor.timeout=86400 --to notebook --execute --stdout examples/attention.ipynb > /dev/null
    - jupyter-nbconvert --ExecutePreprocessor.timeout=86400 --to notebook --execute --stdout examples/activation_maximization.ipynb > /dev/null
